---
# install jdk 8
- file: path=/home/{{ kafka_user }}/zookeeper state=directory owner={{ kafka_user }} mode=750

- name: Copy zookeeper config file
  template: src=zookeeper.properties dest=/home/{{ kafka_user }}/kafka/kafka11/config/zookeeper.properties owner={{ kafka_user }}
