---
# ping
- command: /bin/echo hello

# install jdk 8
- file: path=/home/{{ hadoop_user }}/jdk state=directory owner={{ hadoop_user}} mode=750
- copy: src=software/jdk-8u144-linux-x64.tar.gz dest=/home/{{ hadoop_user }}/jdk
- unarchive: src=/home/{{ hadoop_user }}/jdk/jdk-8u144-linux-x64.tar.gz dest=/home/{{ hadoop_user }}/jdk owner={{ hadoop_user}} creates=/home/{{ hadoop_user }}/jdk/jdk1.8.0_144 copy=no
- lineinfile: dest=/home/{{ hadoop_user }}/.bashrc regexp="^export JAVA_HOME" line="export JAVA_HOME=/home/{{ hadoop_user }}/jdk/jdk1.8.0_144"
#- lineinfile: dest=/home/{{ hadoop_user }}/.bashrc regexp="PATH=" line="export PATH=$PATH:$JAVA_HOME/bin"

# install hadoop
- file: path=/home/{{ hadoop_user }}/hadoop state=directory owner={{ hadoop_user}} mode=750
- name: Download hadoop
  get_url: url={{ hadoop_download_url }} dest=/home/{{ hadoop_user }}/hadoop/hadoop-2.8.1.tar.gz

- name: Extract hadoop archive
  unarchive: src=/home/{{ hadoop_user }}/hadoop/hadoop-2.8.1.tar.gz dest=/home/{{ hadoop_user }}/hadoop owner={{ hadoop_user}} creates=/home/{{ hadoop_user }}/hadoop/hadoop-2.8.1 copy=no

- lineinfile: dest=/home/{{ hadoop_user }}/.bashrc regexp="HADOOP_HOME=" line="export HADOOP_HOME=/home/{{ hadoop_user }}/hadoop/hadoop-2.8.1"
- lineinfile: dest=/home/{{ hadoop_user }}/.bashrc regexp="PATH=" line="export PATH=$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin"

# name: Build hosts file
- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='{{ item.hostname }}' line="{{ item.ip }} {{ item.hostname }}" state=present
  with_items: "{{ nodes }}"

- lineinfile: dest=/etc/hosts regexp='{{ item.hostname }}' line="{{ item.ip }} {{ item.hostname }}" state=present
  with_items: "{{ kafka_nodes }}"

- lineinfile: dest=/etc/hosts regexp='127.0.1.1' state=absent

- file: path=/home/{{ hadoop_user }}/tmp state=directory owner={{ hadoop_user}} mode=750
- file: path=/home/{{ hadoop_user }}/hadoop-data/hdfs/namenode state=directory owner={{ hadoop_user}} mode=750
- file: path=/home/{{ hadoop_user }}/hadoop-data/hdfs/datanode state=directory owner={{ hadoop_user}} mode=750

- name: Add hadoop config files
  template: src={{ item.src }} dest={{ item.dest }} owner={{ hadoop_user}}
  with_items:
    - {src: "core-site.xml", dest: "/home/{{ hadoop_user }}/hadoop/hadoop-2.8.1/etc/hadoop/core-site.xml"}
    - {src: "hdfs-site.xml", dest: "/home/{{ hadoop_user }}/hadoop/hadoop-2.8.1/etc/hadoop/hdfs-site.xml"}
    - {src: "yarn-site.xml", dest: "/home/{{ hadoop_user }}/hadoop/hadoop-2.8.1/etc/hadoop/yarn-site.xml"}
    - {src: "mapred-site.xml", dest: "/home/{{ hadoop_user }}/hadoop/hadoop-2.8.1/etc/hadoop/mapred-site.xml"}
    - {src: "kafka.properties", dest: "/home/{{ hadoop_user }}/hadoop/kafka.properties"}

- lineinfile: dest=/home/{{ hadoop_user }}/hadoop/hadoop-2.8.1/etc/hadoop/hadoop-env.sh regexp="^export JAVA_HOME" line="export JAVA_HOME=/home/{{ hadoop_user }}/jdk/jdk1.8.0_144"

# copy master public key
- authorized_key: user={{ hadoop_user }} state=present key="{{ lookup('file', '/Users/isuru/research/ansible/jetstream-setup/roles/common/templates/master_rsa_pub') }}"
